spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/warehouse
    driverClassName: org.h2.Driver
    username: sa
    password: wh
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000

file:
  upload-dir: src/main/resources/static/uploads/
